spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpa-filters
    username: jpa-filters
    password: 123
  liquibase:
    change-log: classpath:liquibase/migration.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082